### PR TITLE
Fix tests, small changes

### PR DESCRIPTION
**Pull request by luwes**
@heyheyhello 

I fixed up a test, `api.hs` is used in some other packages and I think I would prefer to keep that uniform to `api.h` both of which could be overriden.

`svgJSX` is good but I'm not sure if it should be in the core. 
wouldn't this be a good utility function in the codebase of the user?

also is the `api.s` counting needed for nesting?
I might need to change the api.hs function then

--- 

some lint errors 

Screen Shot 2020-06-07 at 9 14 59 PM

### CODE REVIEW

**Comment by heyheyhello** [comment]
Hey that's so great thanks! I don't know JSDoc typings as well as Typescript, and VSCode's interpreter seems to be pretty flexible beyond the JSDoc spec - so if I hover on an element and it's the type I want then I was considering it OK. Thanks for fixing them to be valid types.

**Comment by heyheyhello** [comment]
I can't push to the types-api branch for some reason. No permission. I can make another PR? I have some other edits for typings.

**Comment by heyheyhello** [comment]
Sorry this is getting so messy. First time working on GitHub. See #114 and this concern here: https://github.com/heyheyhello/sinuous/pull/1#issuecomment-640360166

**Comment by samadadi** [comment]
> `svgJSX` is good but I'm not sure if it should be in the core.
> wouldn't this be a good utility function in the codebase of the user?
> 
I agree with @luwes . I think It is better to let the user decide. But there should be guide in documentation section to the users. Again great work and great library.

**Pull request merged**
