### PR TITLE
Typescript definition changes and explaining Sinuous internals

### PR DESCRIPTION
**Pull request by luwes**
I've been trying to understand how Sinuous works a bit better since I'm writing taping into the API calls, mostly `api.add`, to have tracing of its execution. Running into issues where it's hard to understand how data flows through. Some of the JSDoc types aren't as details as they could be, for instance, I believe `api.add(parent, value, endMark)` could be given a DocumentFragment or an Array as a `value` but the JSDoc just says "Node" (I understand that a fragment is an instance of Node but it's not super clear).

Update: I actually finished the project that prompted all these commits/PRs into Sinuous. I was trying to add onAttach/onDetach hooks without using MutationObserver and needed to better understand how api.add/insert/h worked but I figured it out in the end. Added some comments in this PR for anyone who comes after me...

### CODE REVIEW

**Comment by heyheyhello** [comment]
Hey @luwes! Hope you're well ☀

It's been a minute, had to go back and see what the PRs were about. Thought I'd mention I'm happy to have criticism or hash out some requests for changes if you have them! Although maybe Github's not the best place to have quick chats about it - I don't see my opinion as necessarily being right for the project, especially since I'm over in JSX+TypeScript land at https://gitlab.com/nthm/stayknit which I know is not the project's main focus.

Do tell me if I'm being a lot with all the PRs and such okay?

Speaking of, if there's interest, I'll look into making a JSX-ready starter kit once I have a few things sorted out. I'm trying to pat down SSR rn and then look into packaging lifecycle support as a module so... bit of a todo list

**Comment by luwes** [comment]
hey @heyheyhello, thanks I'm good. I was offline for a bit, re-energizing 🙂 

it's great, thanks for the work you put in! I'm all for getting more people involved in the library. if it's beneficial to a lot of users I've no problem of adding contributions. just don't want to really make it a full framework, more like lightweight utilities. that's why I prefer some things to be external add-ons.

but I'm happy to check out the JSX-ready starter kit, let me know when you have some more.

**Comment by luwes** [comment]
really cool you made the `onAttach` `onDetach` lifecycles without mutation observer. @mindplay-dk requested that feature too, discussed it here https://github.com/luwes/sinuous/issues/89

is your code for the lifecycles public? 
feel free to post it in that thread or a link...

**Comment by heyheyhello** [comment]
Yes absolutely it's all in https://gitlab.com/nthm/stayknit/-/tree/work/src/trace folder of the project. I've been meaning to package it as a module (there's a package.json script to test a bundle but nothing official yet). The website nthm.gitlab.io/stayknit has it running and your browser devtools will download source maps automatically so all the code should be debuggable/viewable in the browser.

Everything is in "tracer.tsx", which defines the general base. Lifecycles are basically a "plugin" for now, that taps into a specific area of the tracer execution. There's a component in "AttachTest.tsx" that makes use of onAttach/onDetach if you want an example of how to write a component that uses it.

**Comment by mindplay-dk** [comment]
I took a look at the [sinuous-lifecycle](https://www.npmjs.com/package/sinuous-lifecycle) package - being able to do this without `MutationObserver` is very neat.

I don't think this is exactly what I've been looking for though - the `onDetach` life-cycle simply reports the fact, it doesn't provide a means of deferring the removal, does it?

(Really, my only use-case and main reason I want that feature for removal animations, which can really help with user perception vs things popping out of existence and other items kind of jumping around. It's possible there's another way to implement that though - perhaps something along the lines of transition groups in React? e.g. a list reconciler that enables deferred removals...)

**Comment by heyheyhello** [comment]
@mindplay-dk Yeah `sinuous-lifecycle` is mostly for coordinating event listeners and side effects - maybe like set the document `<title>` on attach, or send some `fetch()` calls, or set a fade-in animation, etc. I didn't build it to do removal animations but I see the appeal. I feel like making a list reconciler is probably much out of the scope of Sinuous but should be doable in userland code to maintain references to removes that are about to be removed. I made you a codesandbox to illustrate how some of this could be possible:

You'll see that when you click the button, all previous 0..N list items are removed, and then a new list is made of 0..N+1 items. The _second_ button push will try to remove the first element, but I catch it, and move it elsewhere, where I can remove it afterwards on my own terms. It's not "delaying" removal, it's evading it.

Peek 2020-07-09 09-44


https://codesandbox.io/s/sinuous-lifecycle-remove-transition-7r2ns

Note that I'm moving the node to a new parent _outside_ of the list - if you wanted to maintain list order that might be tough... Maybe you could add a list element directly above the once that's to-be-removed, and then move the children of the to-be-removed into the above new-parent, mainting list order. It's not pretty, and if you were actually going to use it it'd need a lot of work.

@luwes If you have a sec there's a weird bug in the sandbox above where `api.rm` is supposed to iterate over a list of children to remove them, but if I reparent one child then all children after that are untouched. Haven't been able to figure out why.

**Comment by luwes** [comment]
@heyheyhello could it be this condition?
https://github.com/luwes/sinuous/blob/4befba076e369a6fff5807328bdb9d0204c1019b/packages/sinuous/h/src/remove-nodes.js#L10-L10

**Pull request merged**
